### PR TITLE
Update arf.json

### PR DESCRIPTION
**Pull request by Theblood**
update:
infoflow.cloud is integrated, a public search engine for people living in Chile

### CODE REVIEW

**Comment by QWERTAL124** [comment]
Has this information been stolen? (Chile )

**Comment by Theblood** [comment]
Under no criteria has this information been stolen, what has been done is reverse engineering of different portals so that certain data can be crossed, using scraping.

**Comment by Theblood** [comment]
@QWERTAL124 @Paul2d @michenriksen @melvin2001 Hello everyone and sorry for the mention but it's been many days, does anyone know why this is not accepted?

**Comment by michenriksen** [comment]
@Theblood I am not a maintainer of this project, so I wonder why you mention me.

I'm sure the maintainer(s) will check it out when they have time and capacity to do so. There is no SLA for PR and issue handling in open-source.

**Comment by 0x4rk0** [comment]
I don't think pull requests are frequently checked. I've had a pull request open for years https://github.com/lockfale/OSINT-Framework/commit/9ce8b5f83a9a1387533965b2bee63390288d8dc2

**Pull request merged**
