### PR TITLE
Add PimEyes Search Engine under Image Search

### PR DESCRIPTION
**Pull request by LeoFibo**
Add PimEyes face recognition search engine under image search in arf.json
https://pimeyes.com/en

### CODE REVIEW

**Comment by Papadope** [comment]
Just saw your pr. Really useful tool and I was just adding that too myself, before I check first the pull requests. Why is not updated on website? 🤔

**Comment by LeoFibo** [comment]
Yeah. I was wondering that too. This tool works really well. the maintainers haven't looked at my pr it seems

**Comment by Papadope** [comment]
Seems like no one did any updates for 2 months now so they might see it anytime soon 🙏

**Comment by s0lray** [comment]
The maintainer is pretty terrible...

**Pull request merged**
